Date range clarity
IHE/ITI.MHD pull request #209
Opened 2023-06-15 22:48 UTC by JohnMoehrke

Apply approved CP-ITI-1254-03
close #129

2023-06-15 22:49 UTC, JohnMoehrke commented
This is a new pull request as the old branch included old files that were being revived. This is the same change, just in a more clean pull request

2023-07-03 14:44 UTC, oliveregger requested changes
The text to the 3.18.4.1.2.3.3 Date/Time Coding at line 2317 should be adapted:

Section 3.18.4.1.2.3.3 Date/Time Coding at line 2317

All Date/time values are to be inclusive **for the lower bound and exclusive for the upper bound**, interpreted as:

2023-07-03 16:02 UTC, JohnMoehrke commented
> The text to the 3.18.4.1.2.3.3 Date/Time Coding at line 2317 should be adapted:
> 
> Section 3.18.4.1.2.3.3 Date/Time Coding at line 2317
> 
> All Date/time values are to be inclusive **for the lower bound and exclusive for the upper bound**, interpreted as:

This change was done to ITI-18. See pull-request on ITI-18.html https://github.com/IHE/publications/pull/296

2023-07-03 19:39 UTC, oliveregger approved these changes

2023-07-03 19:39 UTC, oliveregger commented
@JohnMoehrke thanks, i was not aware of that

2023-07-26 18:05 UTC, merged